[General]
DisplayServer=wayland
GreeterEnvironment=QML_IMPORT_PATH=/usr/lib/qt6/qml

[Autologin]
User=mars
Session=plasmawayland

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Inter,10,-1,5,50,0,0,0,0,0
